language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli bower
before_script:
- bower install
script:
- grunt test
deploy:
  provider: npm
  email: npm@naneau.net
  api_key:
    secure: ZiancrcLVZjxU7cXbW2k+QMlC1g2UaRD3CQhXBays+iVcHYFLOfOxOMZBwwo3E9+MfQ8xzQTv52W1BaYqfMhravbMpXfBIo4ofgGq1yVXoxXmDzpKyzHxguGvB3h8qbYWjKFtHUFkmIpPvUPwvhW/hmc2hcqqZVXXxm6aORSg1s=
  on:
    tags: true
    repo: naneau/gunther
