// Generated by CoffeeScript 1.3.1
(function() {
  var Backbone, BoundProperty, Gunther, ItemSubView, htmlElement, _, _fn, _i, _len, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Gunther = {};

  if (typeof require !== "undefined" && require !== null) {
    module.exports = Gunther;
    _ = require('underscore');
    Backbone = require('backbone');
  } else {
    window.Gunther = Gunther;
    _ = window._, Backbone = window.Backbone;
  }

  if ((typeof _) === !'function') {
    throw 'Underscore.js must be loaded for Gunther to work';
  }

  Gunther.IDGenerator = (function() {

    IDGenerator.name = 'IDGenerator';

    function IDGenerator() {
      this.value = 0;
    }

    IDGenerator.prototype.generate = function() {
      return this.value++;
    };

    return IDGenerator;

  })();

  Gunther.HTML = (function() {

    HTML.name = 'HTML';

    function HTML() {}

    HTML.elements = ["a", "abbr", "address", "article", "aside", "audio", "b", "bdi", "bdo", "blockquote", "body", "button", "canvas", "caption", "cite", "code", "colgroup", "datalist", "dd", "del", "details", "dfn", "div", "dl", "dt", "em", "fieldset", "figcaption", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5", "h6", "head", "header", "hgroup", "html", "i", "iframe", "ins", "kbd", "label", "legend", "li", "map", "mark", "menu", "meter", "nav", "noscript", "object", "ol", "optgroup", "option", "output", "p", "pre", "progress", "q", "rp", "rt", "ruby", "s", "samp", "script", "section", "select", "small", "span", "strong", "style", "sub", "summary", "sup", "table", "tbody", "td", "textarea", "tfoot", "th", "thead", "time", "title", "tr", "u", "ul", "video", "area", "base", "br", "col", "command", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr", "applet", "acronym", "bgsound", "dir", "frameset", "noframes", "isindex", "listing", "nextid", "noembed", "plaintext", "rb", "strike", "xmp", "big", "blink", "center", "font", "marquee", "multicol", "nobr", "spacer", "tt", "basefont", "frame", "date"];

    HTML.eventNames = ['load', 'unload', 'blur', 'change', 'focus', 'reset', 'select', 'submit', 'abort', 'keydown', 'keyup', 'keypress', 'click', 'dblclick', 'mousedown', 'mouseout', 'mouseover', 'mouseup'];

    return HTML;

  })();

  BoundProperty = (function() {

    BoundProperty.name = 'BoundProperty';

    function BoundProperty(model, propertyNames, valueGenerator) {
      var propertyName, _i, _len, _ref,
        _this = this;
      this.model = model;
      this.propertyNames = propertyNames;
      this.valueGenerator = valueGenerator;
      if (!(this.valueGenerator != null) && typeof this.propertyNames === 'string') {
        this.valueGenerator = function() {
          return _this.model.get(_this.propertyNames[0]);
        };
      }
      this.propertyNames = [].concat(this.propertyNames);
      _ref = this.propertyNames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        propertyName = _ref[_i];
        this.model.bind("change:" + propertyName, function() {
          return _this.trigger('change', _this.getValue());
        });
      }
    }

    BoundProperty.prototype.getValue = function() {
      var generatedValue;
      generatedValue = this.valueGenerator();
      if (generatedValue instanceof Gunther.Template) {
        return generatedValue.render();
      } else {
        return generatedValue;
      }
    };

    BoundProperty.prototype.getValueInEl = function(el) {
      var element, generatedValue, _i, _len, _results;
      generatedValue = this.valueGenerator();
      if (generatedValue instanceof Gunther.Template) {
        return generatedValue.renderInto(el, this.model);
      } else if (generatedValue instanceof Backbone.View) {
        generatedValue.el = el;
        return generatedValue.render();
      } else {
        if (el.length > 0) {
          _results = [];
          for (_i = 0, _len = el.length; _i < _len; _i++) {
            element = el[_i];
            _results.push(element.textContent = generatedValue);
          }
          return _results;
        } else {
          return el.textContent = generatedValue;
        }
      }
    };

    return BoundProperty;

  })();

  _.extend(BoundProperty.prototype, Backbone.Events);

  ItemSubView = (function(_super) {

    __extends(ItemSubView, _super);

    ItemSubView.name = 'ItemSubView';

    function ItemSubView() {
      return ItemSubView.__super__.constructor.apply(this, arguments);
    }

    ItemSubView.generator = new Gunther.IDGenerator;

    ItemSubView.prototype.initialize = function(options) {
      var _this = this;
      this.key = "_subview-" + (ItemSubView.generator.generate());
      this.elementKey = "element-" + this.key;
      this.prepend = options.prepend != null ? options.prepend : false;
      this.generator = options.generator;
      this.renderedItems = {};
      this.model.each(function(item) {
        return _this.initItem(item);
      });
      this.model.bind('add', function(item) {
        return _this.addItem(item);
      });
      this.model.bind('remove', function(item) {
        return _this.removeItem(item);
      });
      return this.model.bind('reset', function(newItems) {
        var item, key, _ref;
        _ref = _this.renderedItems;
        for (key in _ref) {
          item = _ref[key];
          _this.removeItem(item);
        }
        return newItems.each(function(item) {
          return _this.addItem(item);
        });
      });
    };

    ItemSubView.prototype.addItem = function(item) {
      this.initItem(item);
      return this.renderItem(item);
    };

    ItemSubView.prototype.removeItem = function(item) {
      if (!(item[this.key] != null)) {
        return;
      }
      if (item[this.key] instanceof Backbone.View) {
        item[this.key].remove();
      } else {
        item[this.elementKey].remove();
      }
      return delete this.renderedItems[item.cid];
    };

    ItemSubView.prototype.initItem = function(item) {
      return item[this.key] = this.generator(item);
    };

    ItemSubView.prototype.renderItem = function(item) {
      if (item[this.key] instanceof Gunther.Template) {
        item[this.elementKey] = item[this.key].render(item);
      } else if (item[this.key] instanceof Backbone.View) {
        item[this.key].render();
        item[this.elementKey] = item[this.key].el;
      } else {
        throw new Error('Generator must return either a Gunther.Template or a Backbone.View instance');
      }
      if (this.prepend) {
        this.el.prepend(item[this.elementKey]);
      } else {
        this.el.append(item[this.elementKey]);
      }
      return this.renderedItems[item.cid] = item;
    };

    ItemSubView.prototype.render = function() {
      var _this = this;
      return this.model.each(function(item) {
        return _this.renderItem(item);
      });
    };

    return ItemSubView;

  })(Backbone.View);

  Gunther.Template = (function() {

    Template.name = 'Template';

    Template.domParsers = [];

    Template.createHtmlElement = function(tagName) {
      return $(document.createElement(tagName));
    };

    Template.addAttributes = function(el, attributes) {
      var attribute, attributeName, attributeValue, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = attributes.length; _i < _len; _i++) {
        attribute = attributes[_i];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (attributeName in attribute) {
            attributeValue = attribute[attributeName];
            _results1.push((function(attributeName, attributeValue) {
              if (_.include(Gunther.HTML.eventNames, attributeName)) {
                return el.bind(attributeName, function() {
                  var args;
                  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                  return attributeValue.apply(null, args);
                });
              } else if (attributeValue instanceof BoundProperty) {
                el.attr(attributeName, attributeValue.getValue());
                return attributeValue.bind('change', function(newValue) {
                  return el.attr(attributeName, newValue);
                });
              } else {
                return el.attr(attributeName, attributeValue);
              }
            })(attributeName, attributeValue));
          }
          return _results1;
        })());
      }
      return _results;
    };

    Template.generateChildren = function(el, childFn, scope) {
      var childResult;
      childResult = childFn.apply(scope);
      if (childResult === void 0) {
        return;
      }
      if (typeof childResult !== 'object') {
        el.append(document.createTextNode(childResult));
      }
      if (childResult instanceof BoundProperty) {
        childResult.getValueInEl(el);
        return childResult.bind('change', function(newVal) {
          el.empty();
          return childResult.getValueInEl(el);
        });
      } else if (childResult instanceof Backbone.View) {
        childResult.el = el;
        return childResult.render();
      }
    };

    function Template(fn) {
      this.fn = fn;
      null;

    }

    Template.prototype.render = function() {
      var args, child, children, domParser, _i, _j, _len, _len1, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.root = $('<div />');
      this.current = this.root;
      this.fn.apply(this, args);
      children = this.root.children();
      _ref = Gunther.Template.domParsers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        domParser = _ref[_i];
        for (_j = 0, _len1 = children.length; _j < _len1; _j++) {
          child = children[_j];
          domParser(child);
        }
      }
      return children;
    };

    Template.prototype.renderInto = function() {
      var args, child, el, _i, _len, _ref;
      el = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      _ref = this.render.apply(this, args);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        ($(el)).append(child);
      }
      return new Backbone.View({
        el: $(el)
      });
    };

    Template.prototype.text = function(text) {
      var childResult, el;
      el = document.createTextNode('');
      if (typeof text === 'string') {
        el.nodeValue = text;
      } else {
        if (typeof text === 'function') {
          childResult = text.apply(this);
        }
        if (childResult instanceof BoundProperty) {
          el.nodeValue = childResult.getValue();
          childResult.bind('change', function(newVal) {
            return el.nodeValue = newVal;
          });
        }
      }
      return this.current.append(el);
    };

    Template.prototype.addElement = function() {
      var args, current, el, tagName;
      tagName = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      current = this.current;
      el = Gunther.Template.createHtmlElement(tagName);
      this.current = el;
      if (typeof args[args.length - 1] === 'function') {
        Gunther.Template.generateChildren(el, args.pop(), this);
      } else if (typeof args[args.length - 1] === 'string') {
        el.nodeValue = args.pop();
      }
      Gunther.Template.addAttributes(el, args);
      current.append(el);
      this.current = current;
      return null;
    };

    Template.prototype.append = function(element) {
      if (element instanceof Backbone.View) {
        element.render();
        return this.current.append(element.el);
      } else {
        return this.current.append(element);
      }
    };

    Template.prototype.subTemplate = function() {
      var args, template;
      template = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return template.renderInto.apply(template, [this.current].concat(__slice.call(args)));
    };

    Template.prototype.bind = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(BoundProperty, args, function(){});
    };

    Template.prototype.itemSubView = function(options) {
      return new ItemSubView(options);
    };

    Template.prototype.e = function() {
      var args, tagName;
      tagName = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.addElement.apply(this, [tagName].concat(__slice.call(args)));
    };

    Template.prototype.t = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.text.apply(this, args);
    };

    return Template;

  })();

  _ref = Gunther.HTML.elements;
  _fn = function(htmlElement) {
    return Gunther.Template.prototype[htmlElement] = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.addElement.apply(this, [htmlElement].concat(__slice.call(args)));
    };
  };
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    htmlElement = _ref[_i];
    _fn(htmlElement);
  }

}).call(this);
